webserver:
  container_name: webserver
  image: webdevops/php-nginx-dev:7.2
  volumes:
    - ./:/var/www
  links:
    - database
  environment:
    - WEB_DOCUMENT_ROOT=/var/www/web
    - WEB_DOCUMENT_INDEX=app_dev.php
  ports:
    - "80:80"

database:
  container_name: database
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=symfony
    - MYSQL_USER=symfony
    - MYSQL_PASSWORD=symfony
  ports:
    - "3306:3306"
