AppBundle\Entity\CustomerOrder:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CustomerOrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        orderDate:
            type: datetime
        shippedDate:
            type: datetime
        status:
            type: string
            length: 255
        comments:
            type: text
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        customer:
            targetEntity: AppBundle\Entity\Customer
            inversedBy: customerOrders
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
